version: '3.1'

services:

  # Temporary nginx server to answer the Let's Encrypt's challenge
  letsencrypt-nginx:
    container_name: 'letsencrypt-nginx'
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx-challenge.conf:/etc/nginx/conf.d/default.conf
      - /dojot/letsencrypt-site:/usr/share/nginx/html
    networks:
      - default
